# Generated by Django 5.2.10 on 2026-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'SuperUser'), ('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter')], default='RECRUITER', max_length=20),
        ),
    ]
