# Generated by Django 5.2.10 on 2026-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AddField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
